## NORMALIZATION
###     Gaussian normalization - (x-mean)stddev  ( values between -10,10 )
###     Min-max normalization 

## Encoding Categorical Data
   ##     sex(male,female) - +1,-1 instead of binary 0,1
   ##     3 values - 1-of-(C-1) encoding 01,10, -1,-1
   ##     4 values - 1-of-(C-1) dummy-coding 0001,0010,0100,1000

https://visualstudiomagazine.com/articles/2014/01/01/how-to-standardize-data-for-neural-networks.aspx

In [4]:
import numpy as np

In [5]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    x_norm = np.linalg.norm(x,axis=1,keepdims=True)
    
    # Divide x by its norm.
    x = x/x_norm
    ### END CODE HERE ###

    return x

In [6]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[ 0.          0.6         0.8       ]
 [ 0.13736056  0.82416338  0.54944226]]


In [7]:
# Min/Max normalization
# Normalized [0,1]
b = (x- np.max(x))/-np.ptp(x)
b

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.83333333, -0.        ,  0.33333333]])

In [8]:
# Normalized [0,255] as integer
c = (255*(x - np.max(x))/-np.ptp(x)).astype(int)
c

array([[255, 127,  85],
       [212,   0,  85]])

In [9]:
#Scale
from sklearn.preprocessing import scale
d = scale( x, axis=0, with_mean=True, with_std=True, copy=True )
d

C:\Users\mwnuk\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int32 was converted to float64 by the scale function.
  warnings.warn(msg, _DataConversionWarning)


array([[-1., -1.,  0.],
       [ 1.,  1.,  0.]])

In [10]:
f= (x - np.mean(x)) / np.std(x)
x

array([[0, 3, 4],
       [1, 6, 4]])

## SKLEARN preprocessing  Standarizing
### http://scikit-learn.org/stable/modules/preprocessing.html

In [14]:
# transform the data to center it by removing the mean value of each feature, 
# then scale it by dividing non-constant features by their standard deviation

from sklearn import preprocessing
import numpy as np
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
X_scaled = preprocessing.scale(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [15]:
#values between 0-1

min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_train_minmax



array([[ 0.5       ,  0.        ,  1.        ],
       [ 1.        ,  0.5       ,  0.33333333],
       [ 0.        ,  1.        ,  0.        ]])