## NORMALIZATION
###     Gaussian normalization - (x-mean)stddev  ( values between -10,10 )
###     Min-max normalization 

## Encoding Categorical Data
   ##     sex(male,female) - +1,-1 instead of binary 0,1
   ##     3 values - 1-of-(C-1) encoding 01,10, -1,-1
   ##     4 values - 1-of-(C-1) dummy-coding 0001,0010,0100,1000

https://visualstudiomagazine.com/articles/2014/01/01/how-to-standardize-data-for-neural-networks.aspx

In [4]:
import numpy as np

In [5]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    x_norm = np.linalg.norm(x,axis=1,keepdims=True)
    
    # Divide x by its norm.
    x = x/x_norm
    ### END CODE HERE ###

    return x

In [6]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[ 0.          0.6         0.8       ]
 [ 0.13736056  0.82416338  0.54944226]]


In [7]:
# Min/Max normalization
# Normalized [0,1]
b = (x- np.max(x))/-np.ptp(x)
b

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.83333333, -0.        ,  0.33333333]])

In [8]:
# Normalized [0,255] as integer
c = (255*(x - np.max(x))/-np.ptp(x)).astype(int)
c

array([[255, 127,  85],
       [212,   0,  85]])

In [9]:
#Scale
from sklearn.preprocessing import scale
d = scale( x, axis=0, with_mean=True, with_std=True, copy=True )
d

C:\Users\mwnuk\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int32 was converted to float64 by the scale function.
  warnings.warn(msg, _DataConversionWarning)


array([[-1., -1.,  0.],
       [ 1.,  1.,  0.]])

In [10]:
f= (x - np.mean(x)) / np.std(x)
x

array([[0, 3, 4],
       [1, 6, 4]])

## SKLEARN preprocessing  Standarizing
### http://scikit-learn.org/stable/modules/preprocessing.html

In [10]:
# transform the data to center it by removing the mean value of each feature, 
# then scale it by dividing non-constant features by their standard deviation

from sklearn import preprocessing
import numpy as np
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
X_scaled = preprocessing.scale(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [11]:
inversed = scaler.inverse_transform(X_scaled)
print(inversed)

[[  10.         -100.22703843  130.26755886]
 [ 120.22703843   10.          -14.05351177]
 [-100.22703843  120.22703843  -86.21404709]]


In [21]:
#Normalize values between 0-1 per column
   # notice difference between fit and fit_transform
min_max_scaler = preprocessing.MinMaxScaler()
X_train_normaized = min_max_scaler.fit_transform(X_train)
X_train_normaized



array([[ 0.5       ,  0.        ,  1.        ],
       [ 1.        ,  0.5       ,  0.33333333],
       [ 0.        ,  1.        ,  0.        ]])

In [23]:
#inversed = scaler.inverse_transform(X_train_normaized)
#print(inversed)

In [ ]:
# integer encode direction
encoder = LabelEncoder()
values[:,4] = encoder.fit_transform(values[:,4])
# ensure all data is float
values = values.astype('float32')
# normalize features
scaler = MinMaxScaler(feature_range=(0, 1))
scaled = scaler.fit_transform(values)

In [ ]:
# good reading for LSTM
https://machinelearningmastery.com/convert-time-series-supervised-learning-problem-python/

In [24]:
# Normalization 0-1  from Brownlee
##############################################

from pandas import Series
from sklearn.preprocessing import MinMaxScaler

# define contrived series
data = [10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0]

series = Series(data)
print(series)
# prepare data for normalization
values = series.values
values = values.reshape((len(values), 1))
# train the normalization
scaler = MinMaxScaler(feature_range=(0, 1))
scaler = scaler.fit(values)
print('Min: %f, Max: %f' % (scaler.data_min_, scaler.data_max_))
# normalize the dataset and print
normalized = scaler.transform(values)
print(normalized)
# inverse transform and print
inversed = scaler.inverse_transform(normalized)
print(inversed)

0     10.0
1     20.0
2     30.0
3     40.0
4     50.0
5     60.0
6     70.0
7     80.0
8     90.0
9    100.0
dtype: float64
Min: 10.000000, Max: 100.000000
[[ 0.        ]
 [ 0.11111111]
 [ 0.22222222]
 [ 0.33333333]
 [ 0.44444444]
 [ 0.55555556]
 [ 0.66666667]
 [ 0.77777778]
 [ 0.88888889]
 [ 1.        ]]
[[  10.]
 [  20.]
 [  30.]
 [  40.]
 [  50.]
 [  60.]
 [  70.]
 [  80.]
 [  90.]
 [ 100.]]


In [25]:
# Standarize stdev aound zero from Brownlee
##############################################

from pandas import Series
from sklearn.preprocessing import StandardScaler
from math import sqrt

# define contrived series
data = [1.0, 5.5, 9.0, 2.6, 8.8, 3.0, 4.1, 7.9, 6.3]
series = Series(data)
print(series)
# prepare data for normalization
values = series.values
values = values.reshape((len(values), 1))
# train the normalization
scaler = StandardScaler()
scaler = scaler.fit(values)
print('Mean: %f, StandardDeviation: %f' % (scaler.mean_, sqrt(scaler.var_)))
# normalize the dataset and print
standardized = scaler.transform(values)
print(standardized)
# inverse transform and print
inversed = scaler.inverse_transform(standardized)
print(inversed)

0    1.0
1    5.5
2    9.0
3    2.6
4    8.8
5    3.0
6    4.1
7    7.9
8    6.3
dtype: float64
Mean: 5.355556, StandardDeviation: 2.712568
[[-1.60569456]
 [ 0.05325007]
 [ 1.34354035]
 [-1.01584758]
 [ 1.26980948]
 [-0.86838584]
 [-0.46286604]
 [ 0.93802055]
 [ 0.34817357]]
[[ 1. ]
 [ 5.5]
 [ 9. ]
 [ 2.6]
 [ 8.8]
 [ 3. ]
 [ 4.1]
 [ 7.9]
 [ 6.3]]
